### PR TITLE
Branch to work on docs linkml schema

### PR DESCRIPTION
**Pull request by glass-ships**

### CODE REVIEW

**Comment by matentzn** [comment]
@glass-ships is this ready to go?

**Comment by glass-ships** [comment]
I think there _may_ have been some work on this in another branch, but I'm not sure. 
What's in here could probably be pulled in though, I don't think we're making use of the linkml schema in generating the documentation just yet

**Comment by matentzn** [comment]
Your other branch has a lot of cool code for generating dynamic repo docs. I just want to move this forward asap. Will you work in it?

**Comment by glass-ships** [comment]
oh yeah, actually i think that one's in a good enough place to merge to main for now (just did that), i'll maybe let @kevinschaper comment on the state of the linkml schema

**Pull request merged**
